[theme]
primaryColor = "#2CA5A0"  # Teal color from the text "AspireCraft"
backgroundColor = "#2D2B2B"  # Dark background matching the GIF's exact color
secondaryBackgroundColor = "#3C3A3A"  # Slightly lighter dark gray for contrast
textColor = "#FFFFFF"  # White text for readability
font = "sans serif"  # Clean, modern font